class_name CardForge
extends RefCounted

## The card creator's pricing model: what each choice on a card is worth, and
## the definition those choices add up to.
##
## A created card does not set its own Energy cost. Every choice has a price in
## points, the prices are added up, and the card's printed cost is what that
## total comes to — so a second point of Attack, or a second card drawn, is
## paid for rather than granted. The player sees the ledger as they build, and
## the card tells them what it is worth.
##
## Nothing here is a new mechanic. Every feature is assembled from the effect
## vocabulary in `src/core/effect_schema.gd`, the rules text is generated by
## `TextGen` like any other card's, and the result is validated by the same
## `CardDef.validate()` as the shipped catalog. A card this file cannot express
## in that vocabulary cannot be created, which is the point: the creator can
## never promise an effect the engine will not perform.

## The exchange rate between what a card does and what it costs to play.
const POINTS_PER_ENERGY := 10
## No card may cost more than this, however much is piled onto it.
const MAX_COST := 12

## A Hero is deliberately not creatable. A Hero has no play cost, so there is
## nothing for the prices to land on, and it would also have to be a unique
## named character with a place in the deck rules. Everything else is fair game.
const TYPES := ["companion", "skill", "equipment", "taahma", "location"]

## What a card is worth before anything is put on it. A Skill is nothing but
## what it does; a body that stays on the board is worth something by standing
## there.
const TYPE_BASE := {
    "companion": 6, "skill": 0, "equipment": 4, "taahma": 3, "location": 6,
}

const STAT_PRICE := {
    "attack": 3,
    "defense": 2,
    ## A Companion that raises your maximum Energy pays for every point of it.
    "energy_contribution": 5,
    ## An Equipment's printed modifiers buff a body that is already on the
    ## board, so they cost more than the same numbers on the body itself.
    "equip_attack": 4,
    "equip_defense": 3,
}

## An attack that costs nothing to declare is worth paying for; one that costs
## two Energy is a discount.
const ATTACK_COST_PRICE := {0: 5, 1: 0, 2: -3}

## A card carrying two Affinities counts for both chains.
const SECOND_AFFINITY_PRICE := 3
## Being playable on your opponent's turn.
const REACTION_PRICE := 4

## Rarity is not chosen either: it follows the total, so a card's mark says
## how much was put into it. Highest threshold first.
const RARITY_STEPS := [
    ["legendary", 55], ["rare", 38], ["uncommon", 20], ["common", 0],
]

## Every feature a created card can take.
##
##   label   what the creator calls it
##   help    one line explaining what it does, shown beside it
##   types   the card types it may go on
##   price   points, multiplied by the amount when the feature takes one
##   amount  the quantity the player picks, if any
##   target  the target the card must ask for, if any (Skills only)
##
## The effect data itself is built by `_effects_for`, which is the one place
## that has to agree with the effect schema.
const FEATURES := {
    # --- Skills ---------------------------------------------------------------
    "damage": {
        "label": "Deal damage", "price": 5, "types": ["skill"],
        "help": "Deal damage to a character your opponent controls. Defense reduces it.",
        "amount": {"min": 1, "max": 6, "default": 2, "caption": "Damage"},
        "target": {"kind": "opponent_character"},
    },
    "pierce": {
        "label": "Deal damage, ignoring Defense", "price": 7, "types": ["skill"],
        "help": "Deal damage to a character your opponent controls, whatever its Defense.",
        "amount": {"min": 1, "max": 5, "default": 1, "caption": "Damage"},
        "target": {"kind": "opponent_character"},
    },
    "burn_hero": {
        "label": "Damage the opposing Hero", "price": 6, "types": ["skill"],
        "help": "Deal damage straight to your opponent's Hero.",
        "amount": {"min": 1, "max": 5, "default": 1, "caption": "Damage"},
    },
    "draw": {
        "label": "Draw cards", "price": 5, "types": ["skill"],
        "help": "Draw from your Hit Deck.",
        "amount": {"min": 1, "max": 4, "default": 1, "caption": "Cards"},
    },
    "energy": {
        "label": "Gain Energy", "price": 9, "types": ["skill"],
        "help": "Gain Energy, up to your maximum.",
        "amount": {"min": 1, "max": 4, "default": 1, "caption": "Energy"},
    },
    "drain": {
        "label": "Drain your opponent's Energy", "price": 8, "types": ["skill"],
        "help": "Your opponent loses Energy they have not spent.",
        "amount": {"min": 1, "max": 4, "default": 1, "caption": "Energy"},
    },
    "destroy": {
        "label": "Destroy a Companion", "price": 22, "types": ["skill"],
        "help": "Destroy a Companion your opponent controls. It is wounded.",
        "target": {"kind": "opponent_companion"},
    },
    "bounce": {
        "label": "Return a Companion to hand", "price": 12, "types": ["skill"],
        "help": "Send a Companion your opponent controls back to their hand.",
        "target": {"kind": "opponent_companion"},
    },
    "buff": {
        "label": "Grant Attack for the round", "price": 3, "types": ["skill"],
        "help": "A character you control attacks harder until Round End.",
        "amount": {"min": 1, "max": 5, "default": 2, "caption": "Attack"},
        "target": {"kind": "own_character"},
    },
    "guard": {
        "label": "Grant Defense for the round", "price": 2, "types": ["skill"],
        "help": "A character you control takes less until Round End.",
        "amount": {"min": 1, "max": 5, "default": 2, "caption": "Defense"},
        "target": {"kind": "own_character"},
    },
    "weaken": {
        "label": "Weaken a character", "price": 3, "types": ["skill"],
        "help": "A character your opponent controls attacks for less until Round End.",
        "amount": {"min": 1, "max": 5, "default": 2, "caption": "Attack"},
        "target": {"kind": "opponent_character"},
    },
    "shield": {
        "label": "Prevent damage", "price": 6, "types": ["skill"],
        "help": "Prevent the next damage dealt to a character you control this round.",
        "amount": {"min": 1, "max": 4, "default": 2, "caption": "Damage"},
        "target": {"kind": "own_character"},
    },
    "mill": {
        "label": "Exhaust your opponent's deck", "price": 3, "types": ["skill"],
        "help": "Cards leave the top of your opponent's Hit Deck for their Exhaust Deck.",
        "amount": {"min": 1, "max": 5, "default": 2, "caption": "Cards"},
    },
    "recover": {
        "label": "Recover from your Exhaust Deck", "price": 6, "types": ["skill"],
        "help": "Take cards back out of your own Exhaust Deck.",
        "amount": {"min": 1, "max": 3, "default": 1, "caption": "Cards"},
    },
    "discard": {
        "label": "Make your opponent exhaust from hand", "price": 7, "types": ["skill"],
        "help": "Your opponent chooses cards in their hand and exhausts them.",
        "amount": {"min": 1, "max": 3, "default": 1, "caption": "Cards"},
    },
    "next_attack": {
        "label": "Bonus to the next attack", "price": 7, "types": ["skill"],
        "help": "The next character you control to attack deals additional damage.",
        "amount": {"min": 1, "max": 4, "default": 1, "caption": "Damage"},
    },
    "chain_damage": {
        "label": "Chain bonus: extra damage", "price": 3, "types": ["skill"],
        "help": "Costs less because it asks for something: two of your own Affinity must"
            + " have resolved earlier in the Action Sequence.",
        "amount": {"min": 1, "max": 6, "default": 3, "caption": "Damage"},
        "target": {"kind": "opponent_character"},
    },

    # --- Companions -----------------------------------------------------------
    "on_deploy_draw": {
        "label": "On deployment, draw", "price": 6, "types": ["companion"],
        "help": "Draw when this Companion arrives.",
        "amount": {"min": 1, "max": 3, "default": 1, "caption": "Cards"},
    },
    "on_deploy_burn": {
        "label": "On deployment, damage the opposing Hero", "price": 6,
        "types": ["companion"],
        "help": "Deal damage to your opponent's Hero when this Companion arrives.",
        "amount": {"min": 1, "max": 4, "default": 1, "caption": "Damage"},
    },
    "on_wounded_draw": {
        "label": "When wounded, draw", "price": 4, "types": ["companion"],
        "help": "Draw when this Companion is wounded, so losing it is not nothing.",
        "amount": {"min": 1, "max": 3, "default": 1, "caption": "Cards"},
    },
    "on_attack_energy": {
        "label": "On its attack, gain Energy", "price": 6, "types": ["companion"],
        "help": "Gain Energy whenever this Companion's attack resolves.",
        "amount": {"min": 1, "max": 3, "default": 1, "caption": "Energy"},
    },
    "aura_attack": {
        "label": "Your Companions attack harder", "price": 7, "types": ["companion"],
        "help": "While this is in play, every Companion you control has more Attack.",
        "amount": {"min": 1, "max": 3, "default": 1, "caption": "Attack"},
    },
    "aura_defense": {
        "label": "Your Companions defend harder", "price": 5, "types": ["companion"],
        "help": "While this is in play, every Companion you control has more Defense.",
        "amount": {"min": 1, "max": 3, "default": 1, "caption": "Defense"},
    },
    "aura_energy": {
        "label": "Raise your maximum Energy", "price": 8, "types": ["companion"],
        "help": "While this is in play, your maximum Energy is higher.",
        "amount": {"min": 1, "max": 3, "default": 1, "caption": "Energy"},
    },
    "affinity_energy": {
        "label": "Answer your own Affinity", "price": 9, "types": ["companion"],
        "help": "Whenever a card of this card's Affinity resolves while it stands in the"
            + " Action Sequence, gain 1 Energy.",
    },
    "reaction_attacks": {
        "label": "Your characters may attack as a Reaction", "price": 16,
        "types": ["companion"],
        "help": "While this is in play, your characters can be committed to attack on your"
            + " opponent's turn.",
    },

    # --- Equipment and Ta'ahma ------------------------------------------------
    "host_attack_burn": {
        "label": "On its host's attack, damage the opposing Hero", "price": 6,
        "types": ["equipment", "taahma"],
        "help": "Deal damage to your opponent's Hero whenever the character wearing this"
            + " resolves an attack.",
        "amount": {"min": 1, "max": 4, "default": 1, "caption": "Damage"},
    },
    "host_melee_bonus": {
        "label": "Its host hits harder in melee", "price": 4,
        "types": ["equipment", "taahma"],
        "help": "Costs less because it asks for something: the bonus applies only while its"
            + " host is attacking with a Melee attack.",
        "amount": {"min": 1, "max": 4, "default": 2, "caption": "Attack"},
    },
    "host_sequence_guard": {
        "label": "Its host is tougher in the Sequence", "price": 4,
        "types": ["equipment", "taahma"],
        "help": "Costs less because it asks for something: the bonus applies only while its"
            + " host stands in the Action Sequence.",
        "amount": {"min": 1, "max": 4, "default": 2, "caption": "Defense"},
    },

    # --- Locations ------------------------------------------------------------
    "field_attack": {
        "label": "Every Companion attacks harder", "price": 8, "types": ["location"],
        "help": "The field favours attack — for both players, as a Location does.",
        "amount": {"min": 1, "max": 3, "default": 1, "caption": "Attack"},
    },
    "field_own_defense": {
        "label": "Your Companions defend harder", "price": 6, "types": ["location"],
        "help": "While this Location is active, every Companion you control has more Defense.",
        "amount": {"min": 1, "max": 3, "default": 1, "caption": "Defense"},
    },
    "round_end_draw": {
        "label": "At Round End, draw", "price": 7, "types": ["location"],
        "help": "Draw at the end of every round while this Location is active.",
        "amount": {"min": 1, "max": 2, "default": 1, "caption": "Cards"},
    },
}


## The design a created card was made from, or an empty dictionary for a card
## that was not made here.
static func design_in(raw: Dictionary) -> Dictionary:
    var block: Variant = raw.get("forge", null)
    if not (block is Dictionary):
        return {}
    var design: Variant = (block as Dictionary).get("design", null)
    return (design as Dictionary).duplicate(true) if design is Dictionary else {}


## A design with every field present and every value the type it should be, so
## what is stored on a card is not shaped by however the screen happened to
## fill it in.
static func normalise(design: Dictionary) -> Dictionary:
    var card_type := String(design.get("type", "skill"))
    var out := blank_design(card_type)
    out["name"] = String(design.get("name", "")).strip_edges()
    out["flavor"] = String(design.get("flavor", ""))
    out["affinities"] = (design.get("affinities", []) as Array).duplicate()
    out["tags"] = (design.get("tags", []) as Array).duplicate()
    out["attack_tags"] = (design.get("attack_tags", []) as Array).duplicate()
    out["attack"] = int(design.get("attack", 0))
    out["defense"] = int(design.get("defense", 0))
    out["attack_cost"] = int(design.get("attack_cost", 1))
    out["energy_contribution"] = int(design.get("energy_contribution", 0))
    out["reaction"] = bool(design.get("reaction", false))
    out["art"] = (design.get("art", {}) as Dictionary).duplicate(true)
    var features: Array = []
    for f in design.get("features", []):
        var feature: Dictionary = f
        var fid := String(feature.get("id", ""))
        if not FEATURES.has(fid):
            continue
        features.append({"id": fid, "amount": _amount_of(feature, fid)})
    out["features"] = features
    return out


## A blank design, ready for the creator screen to fill in.
static func blank_design(card_type: String = "skill", affinity: String = "passion") -> Dictionary:
    return {
        "name": "",
        "flavor": "",
        "type": card_type,
        "affinities": [affinity],
        "tags": [],
        "attack_tags": [],
        "attack": 0,
        "defense": 0,
        "attack_cost": 1,
        "energy_contribution": 0,
        "reaction": false,
        "features": [],     # [{"id": String, "amount": int}]
        "art": {},
    }


## The features a card of this type may take, in table order.
static func features_for(card_type: String) -> Array:
    var out: Array = []
    for fid in FEATURES.keys():
        if (FEATURES[fid]["types"] as Array).has(card_type):
            out.append(String(fid))
    return out


static func feature_amount_spec(feature_id: String) -> Dictionary:
    if not FEATURES.has(feature_id):
        return {}
    return (FEATURES[feature_id] as Dictionary).get("amount", {})


static func takes_amount(feature_id: String) -> bool:
    return not feature_amount_spec(feature_id).is_empty()


# ------------------------------------------------------------------ pricing ---

## What a design is worth, itemised.
##
## Returns {"points": int, "cost": int, "rarity": String, "lines": Array}, where
## each line is {"label": String, "points": int} — the ledger the creator shows,
## so a player can see which choice made the card cost what it does.
static func price(design: Dictionary) -> Dictionary:
    var card_type := String(design.get("type", "skill"))
    var lines: Array = []
    var points := 0

    var base := int(TYPE_BASE.get(card_type, 0))
    if base != 0:
        lines.append({"label": "%s card" % _type_label(card_type), "points": base})
        points += base

    for entry in _stat_lines(design, card_type):
        lines.append(entry)
        points += int((entry as Dictionary)["points"])

    var affinities: Array = design.get("affinities", [])
    if affinities.size() > 1:
        var extra := (affinities.size() - 1) * SECOND_AFFINITY_PRICE
        lines.append({"label": "Second Affinity", "points": extra})
        points += extra

    if bool(design.get("reaction", false)):
        lines.append({"label": "Reaction timing", "points": REACTION_PRICE})
        points += REACTION_PRICE

    for f in design.get("features", []):
        var feature: Dictionary = f
        var fid := String(feature.get("id", ""))
        if not FEATURES.has(fid):
            continue
        var spec: Dictionary = FEATURES[fid]
        var amount := _amount_of(feature, fid)
        var cost := int(spec["price"]) * (amount if takes_amount(fid) else 1)
        var label := String(spec["label"])
        if takes_amount(fid):
            label = "%s (%d)" % [label, amount]
        lines.append({"label": label, "points": cost})
        points += cost

    points = max(0, points)
    return {
        "points": points,
        "cost": cost_for_points(points),
        "rarity": rarity_for_points(points),
        "lines": lines,
    }


## The printed Energy cost a point total comes to. Part of a point is still
## paid for: three points of value is one Energy, not none.
static func cost_for_points(points: int) -> int:
    return int(min(MAX_COST, ceil(float(max(0, points)) / float(POINTS_PER_ENERGY))))


static func rarity_for_points(points: int) -> String:
    for step in RARITY_STEPS:
        if points >= int((step as Array)[1]):
            return String((step as Array)[0])
    return "common"


static func _stat_lines(design: Dictionary, card_type: String) -> Array:
    var out: Array = []
    if card_type == "companion":
        var atk := int(design.get("attack", 0))
        var def := int(design.get("defense", 0))
        var contrib := int(design.get("energy_contribution", 0))
        if atk > 0:
            out.append({"label": "Attack %d" % atk, "points": atk * int(STAT_PRICE["attack"])})
        if def > 0:
            out.append({"label": "Defense %d" % def, "points": def * int(STAT_PRICE["defense"])})
        if contrib > 0:
            out.append({"label": "Adds %d maximum Energy" % contrib,
                "points": contrib * int(STAT_PRICE["energy_contribution"])})
        var ac := int(design.get("attack_cost", 1))
        var ac_price := int(ATTACK_COST_PRICE.get(ac, 0))
        if ac_price != 0:
            out.append({"label": "Attack costs %d Energy" % ac, "points": ac_price})
    elif card_type == "equipment" or card_type == "taahma":
        var eatk := int(design.get("attack", 0))
        var edef := int(design.get("defense", 0))
        if eatk > 0:
            out.append({"label": "Gives its host +%d Attack" % eatk,
                "points": eatk * int(STAT_PRICE["equip_attack"])})
        if edef > 0:
            out.append({"label": "Gives its host +%d Defense" % edef,
                "points": edef * int(STAT_PRICE["equip_defense"])})
    return out


static func _amount_of(feature: Dictionary, feature_id: String) -> int:
    var spec := feature_amount_spec(feature_id)
    if spec.is_empty():
        return 1
    var want := int(feature.get("amount", int(spec.get("default", 1))))
    return clampi(want, int(spec.get("min", 1)), int(spec.get("max", 1)))


# ------------------------------------------------------------ the definition ---

## Problems with a design, in the player's words rather than the schema's.
##
## `catalog` is used to refuse a display name another card already has, since
## two cards sharing a name is a catalog error rather than a matter of taste.
## `own_id` is the card being edited, so re-saving it does not clash with
## itself.
static func design_errors(design: Dictionary, catalog: Catalog = null,
        own_id: String = "") -> Array:
    var errs: Array = []
    var card_type := String(design.get("type", ""))
    if not TYPES.has(card_type):
        errs.append("Pick what kind of card this is.")
    if String(design.get("name", "")).strip_edges() == "":
        errs.append("Give the card a name.")
    var affinities: Array = design.get("affinities", [])
    if affinities.is_empty():
        errs.append("Pick at least one Affinity.")
    if affinities.size() > 2:
        errs.append("A card carries at most two Affinities.")

    var features: Array = design.get("features", [])
    for f in features:
        var fid := String((f as Dictionary).get("id", ""))
        if not FEATURES.has(fid):
            errs.append("'%s' is not a feature this creator knows." % fid)
        elif not (FEATURES[fid]["types"] as Array).has(card_type):
            errs.append("%s cannot go on a %s card." % [
                String(FEATURES[fid]["label"]), _type_label(card_type)])

    # A card has to do something. A body on the board is something; a Skill that
    # does nothing is a blank piece of card.
    if features.is_empty():
        if card_type == "skill":
            errs.append("A Skill needs at least one feature: it is only what it does.")
        elif card_type == "location":
            errs.append("A Location needs at least one feature to change the field.")
        elif card_type == "equipment" or card_type == "taahma":
            if int(design.get("attack", 0)) <= 0 and int(design.get("defense", 0)) <= 0:
                errs.append("Give this either a printed modifier or a feature.")

    # A Reaction is a Skill's timing. Nothing else is played in a window.
    if bool(design.get("reaction", false)) and card_type != "skill":
        errs.append("Only a Skill can be played as a Reaction.")

    # Two features that each ask the player to choose a different target would
    # need two questions on commitment, which the engine asks once.
    var kinds: Dictionary = {}
    for f2 in features:
        var fid2 := String((f2 as Dictionary).get("id", ""))
        if FEATURES.has(fid2) and (FEATURES[fid2] as Dictionary).has("target"):
            kinds[String(((FEATURES[fid2] as Dictionary)["target"] as Dictionary)["kind"])] = true
    if kinds.size() > 1:
        errs.append("These features ask for different targets (%s). A card asks for one."
            % ", ".join(PackedStringArray(kinds.keys())))

    if catalog != null:
        var wanted := String(design.get("name", "")).strip_edges()
        for def in catalog.all_defs():
            var d: CardDef = def
            if d.name == wanted and d.id != own_id:
                errs.append("%s already carries that name." % d.id)
                break
    return errs


## The next free id for a created card of this type.
static func next_id(card_type: String, taken: Dictionary) -> String:
    var stem := "CUSTOM_%s_" % _type_code(card_type)
    var n := 1
    while taken.has(stem + "%03d" % n):
        n += 1
    return stem + "%03d" % n


## Build the card definition a design comes to, priced and with its rules text
## generated. The result is raw data, ready to be validated and stored.
static func build(design: Dictionary, def_id: String) -> Dictionary:
    var card_type := String(design.get("type", "skill"))
    var priced := price(design)
    var affinities: Array = (design.get("affinities", []) as Array).duplicate()
    var reaction := bool(design.get("reaction", false)) and card_type == "skill"

    var raw: Dictionary = {
        "id": def_id,
        "revision": 1,
        "name": String(design.get("name", "")).strip_edges(),
        "types": [card_type],
        "affinities": affinities,
        "rarity": String(priced["rarity"]),
        "tags": _tags_for(design, reaction),
        "cost": {"kind": "fixed", "amount": int(priced["cost"])},
        "authored": true,
        "placeholder": false,
        # The mark that says where this card came from. It is printed on the
        # face, so a created card is never mistaken for one of the game's own.
        "custom": true,
        "flavor": String(design.get("flavor", "")),
        "patterns": ["custom"],
        "effects": [],
        "triggers": [],
    }

    if card_type != "hero":
        raw["timing"] = ["reaction", "action"] if reaction else ["action"]
        if reaction:
            raw["reaction_window"] = "after"

    # Statistics, by what the type actually prints.
    if card_type == "companion":
        raw["attack"] = int(design.get("attack", 0))
        raw["defense"] = int(design.get("defense", 0))
        raw["attack_cost"] = int(design.get("attack_cost", 1))
        raw["energy_contribution"] = int(design.get("energy_contribution", 0))
        var atk_tags: Array = (design.get("attack_tags", []) as Array).duplicate()
        if atk_tags.is_empty():
            atk_tags = ["martial", "melee"]
        raw["attack_tags"] = atk_tags
        raw["persistent"] = {"kind": "companion"}
    elif card_type == "location":
        raw["persistent"] = {"kind": "location"}
    elif card_type == "equipment" or card_type == "taahma":
        raw["attack"] = int(design.get("attack", 0))
        raw["defense"] = int(design.get("defense", 0))
        raw["persistent"] = {"kind": "attachment", "slot": card_type}
        # An attachment played from hand asks which of your characters wears it.
        raw["target"] = {"kind": "own_character_host"}

    # The features, as effects and triggers.
    var target_spec: Dictionary = {}
    for f in design.get("features", []):
        var feature: Dictionary = f
        var fid := String(feature.get("id", ""))
        if not FEATURES.has(fid):
            continue
        var spec: Dictionary = FEATURES[fid]
        if spec.has("target") and card_type == "skill":
            target_spec = (spec["target"] as Dictionary).duplicate(true)
        var built := _effects_for(fid, _amount_of(feature, fid), design)
        (raw["effects"] as Array).append_array(built.get("effects", []))
        (raw["triggers"] as Array).append_array(built.get("triggers", []))
        (raw["patterns"] as Array).append(fid)

    if not target_spec.is_empty():
        raw["target"] = target_spec

    var art: Dictionary = (design.get("art", {}) as Dictionary).duplicate(true)
    if not art.is_empty():
        raw["art"] = art

    # The design is kept on the card. Reading a card's choices back out of its
    # finished effect data would be guesswork, and a creator that cannot reopen
    # what it made is a creator you only get one try at.
    raw["forge"] = {"version": 1, "design": normalise(design)}

    # Text last, generated from the effects that were just assembled, so a
    # created card cannot say anything its own data does not.
    raw["text"] = TextGen.render(CardDef.from_dict(raw))
    return raw


static func _tags_for(design: Dictionary, reaction: bool) -> Array:
    var tags: Array = []
    for t in design.get("tags", []):
        if EffectSchema.TAGS.has(String(t)) and String(t) != "reaction":
            tags.append(String(t))
    if reaction:
        tags.append("reaction")
    return tags


## The effect data one feature comes to. This is the only place in the creator
## that has to agree with the effect schema, and everything it produces is
## validated before it can be saved.
static func _effects_for(feature_id: String, amount: int, design: Dictionary) -> Dictionary:
    var affinity := String((design.get("affinities", ["passion"]) as Array)[0]) \
        if not (design.get("affinities", []) as Array).is_empty() else "passion"
    match feature_id:
        "damage":
            return {"effects": [{"op": "direct_damage", "target": "chosen",
                "amount": amount, "ignores_defense": false}]}
        "pierce":
            return {"effects": [{"op": "direct_damage", "target": "chosen",
                "amount": amount, "ignores_defense": true}]}
        "burn_hero":
            return {"effects": [{"op": "damage_hero", "who": "opponent", "amount": amount}]}
        "draw":
            return {"effects": [{"op": "draw", "who": "self", "amount": amount}]}
        "energy":
            return {"effects": [{"op": "energy_gain", "who": "self", "amount": amount}]}
        "drain":
            return {"effects": [{"op": "energy_drain", "who": "opponent", "amount": amount}]}
        "destroy":
            return {"effects": [{"op": "destroy", "target": "chosen"}]}
        "bounce":
            return {"effects": [{"op": "bounce", "target": "chosen"}]}
        "buff":
            return {"effects": [{"op": "stat_mod", "target": "chosen",
                "duration": "round", "attack": amount}]}
        "guard":
            return {"effects": [{"op": "stat_mod", "target": "chosen",
                "duration": "round", "defense": amount}]}
        "weaken":
            return {"effects": [{"op": "stat_mod", "target": "chosen",
                "duration": "round", "attack": -amount}]}
        "shield":
            return {"effects": [{"op": "prevent_damage", "target": "chosen",
                "amount": amount, "duration": "round"}]}
        "mill":
            return {"effects": [{"op": "mill", "who": "opponent", "amount": amount}]}
        "recover":
            return {"effects": [{"op": "recover_from_exhaust", "who": "self", "amount": amount}]}
        "discard":
            return {"effects": [{"op": "exhaust_from_hand", "who": "opponent",
                "amount": amount, "chooser": "opponent"}]}
        "next_attack":
            return {"effects": [{"op": "next_attack_bonus", "amount": amount,
                "scope": "controller"}]}
        "chain_damage":
            return {"effects": [{"op": "chain_reward",
                "require": {"min": 2, "affinity": affinity, "scope": "controller"},
                "then": [{"op": "direct_damage", "target": "chosen",
                    "amount": amount, "ignores_defense": false}]}]}

        "on_deploy_draw":
            return {"triggers": [{"on": {"kind": "self_deployed"},
                "effects": [{"op": "draw", "who": "self", "amount": amount}]}]}
        "on_deploy_burn":
            return {"triggers": [{"on": {"kind": "self_deployed"},
                "effects": [{"op": "damage_hero", "who": "opponent", "amount": amount}]}]}
        "on_wounded_draw":
            return {"triggers": [{"on": {"kind": "self_wounded"},
                "effects": [{"op": "draw", "who": "self", "amount": amount}]}]}
        "on_attack_energy":
            return {"triggers": [{"on": {"kind": "self_attack_resolved"},
                "effects": [{"op": "energy_gain", "who": "self", "amount": amount}]}]}
        "aura_attack":
            return {"effects": [{"op": "aura_stat_mod", "scope": "own_companions",
                "attack": amount}]}
        "aura_defense":
            return {"effects": [{"op": "aura_stat_mod", "scope": "own_companions",
                "defense": amount}]}
        "aura_energy":
            return {"effects": [{"op": "aura_energy_max", "who": "self", "amount": amount}]}
        "affinity_energy":
            return {"triggers": [{
                "on": {"kind": "affinity_card_resolved", "affinity": affinity,
                    "scope": "controller"},
                "effects": [{"op": "energy_gain", "who": "self", "amount": 1}]}]}
        "reaction_attacks":
            return {"effects": [{"op": "grant_reaction_attack", "who": "self"}]}

        "host_attack_burn":
            return {"triggers": [{"on": {"kind": "host_attack_resolved"},
                "effects": [{"op": "damage_hero", "who": "opponent", "amount": amount}]}]}
        "host_melee_bonus":
            return {"effects": [{"op": "aura_stat_mod", "scope": "host", "attack": amount,
                "cond": {"kind": "host_attacks_with", "tag": "melee"}}]}
        "host_sequence_guard":
            return {"effects": [{"op": "aura_stat_mod", "scope": "host", "defense": amount,
                "cond": {"kind": "host_in_sequence"}}]}

        "field_attack":
            return {"effects": [{"op": "aura_stat_mod", "scope": "all_companions",
                "attack": amount}]}
        "field_own_defense":
            return {"effects": [{"op": "aura_stat_mod", "scope": "own_companions",
                "defense": amount}]}
        "round_end_draw":
            return {"triggers": [{"on": {"kind": "round_end"},
                "effects": [{"op": "draw", "who": "self", "amount": amount}]}]}
    return {}


static func _type_label(card_type: String) -> String:
    return String(TextGen.TYPE_LABEL.get(card_type, card_type.capitalize()))


static func _type_code(card_type: String) -> String:
    match card_type:
        "companion":
            return "COMP"
        "equipment":
            return "EQUIP"
        "taahma":
            return "TAAHMA"
        "location":
            return "LOC"
    return "SKILL"
